package Exceptionhandling;

public class HandleExceptionWithTryCatch {
    public static void main(String[] args) {try {
            System.out.println(10 / 1);
    }
    catch (ArithmeticException arithmeticException){
        System.out.println("divide by zero");
    }
            System.out.println("rest of the code........");
            System.out.println("rest of the code........");
            System.out.println("rest of the code........");
            System.out.println("rest of the code........");
        }
    }
